# Generated by Django 3.2.6 on 2021-08-09 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityPlacesREF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PriorityPlaceNameEnglish', models.CharField(max_length=100, verbose_name='Priority Place (En)')),
                ('PriorityPlaceNameFrench', models.CharField(blank=True, max_length=100, null=True, verbose_name='Priority Place (Fr)')),
            ],
            options={
                'ordering': ['PriorityPlaceNameEnglish'],
            },
        ),
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectLocationNameEnglish', models.CharField(max_length=100, verbose_name='Name (En)')),
                ('ProjectLocationNameFrench', models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Fr)')),
                ('ProjectLocationGeneralDescriptonEnglish', models.TextField(blank=True, null=True, verbose_name='Description (En)')),
                ('ProjectLocationGeneralDescriptonFrench', models.TextField(blank=True, null=True, verbose_name='Description (Fr)')),
                ('ProjectLocationShapeFileSource', models.CharField(blank=True, max_length=100, null=True, verbose_name='Source')),
            ],
            options={
                'ordering': ['ProjectLocationNameEnglish'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProjectTitleEnglish', models.CharField(max_length=250, verbose_name='Title (En)')),
                ('ProjectTitleFrench', models.CharField(blank=True, max_length=250, null=True, verbose_name='Title (Fr)')),
                ('ECCCAssignedProjectIdentfer', models.CharField(max_length=50, unique=True, verbose_name='Proj. Number')),
                ('ProjectPurposeDescriptonEnglish', models.TextField(blank=True, null=True, verbose_name='Description (En)')),
                ('ProjectPurposeDescriptonFrench', models.TextField(blank=True, null=True, verbose_name='Description (Fr)')),
                ('GeneralLocationDescriptonEnglish', models.TextField(blank=True, null=True, verbose_name='General Location (En)')),
                ('GeneralLocationDescriptonFrench', models.TextField(blank=True, null=True, verbose_name='General Location (Fr)')),
                ('created', models.DateField(auto_now_add=True)),
                ('PriorityPlaceUID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pplaces.priorityplacesref')),
                ('ProjectLocation', models.ManyToManyField(to='pplaces.ProjectLocation')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
